pipeline {
    agent {
        label 'Agent'
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('Docker')
        DOCKERFILE = 'primecare-html/Dockerfile'
        CONTAINER_NAME = 'webex'
        IMAGE_NAME = 'joehaddy/webapp'
        IMAGE_TAG = '1.0'
        GIT_REPO_URL = 'https://github.com/joehaddy07/Devops-Jenkins.git'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: "${env.GIT_REPO_URL}", branch: 'main'
            }
        }

        stage('Check Dockerfile') {
            steps {
                script {
                    if (fileExists(env.DOCKERFILE)) {
                        echo "File exists: ${env.DOCKERFILE}"
                    } else {
                        error "File does not exist: ${env.DOCKERFILE}"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${env.IMAGE_NAME}:${env.IMAGE_TAG}", "-f ${env.DOCKERFILE} .")
                }
            }
        }

        stage('Run & Push Docker Image') {
            steps {
                script {
                    sh "docker run --name ${env.CONTAINER_NAME} -d -p 80:80 ${env.IMAGE_NAME}:${env.IMAGE_TAG}"
                    sh "docker images"
                    sh "docker ps -a"
                    docker.withRegistry('https://index.docker.io/v1/', env.DOCKERHUB_CREDENTIALS) {
                        docker.image("${env.IMAGE_NAME}:${env.IMAGE_TAG}").push()
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    sh "docker rmi -f ${env.IMAGE_NAME}:${env.IMAGE_TAG}"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}